language: node_js

before_install:
  - npm install -g dockerfile_lint jsonlint coffeelint

script:

  # Validate Docker files
  - dockerfile_lint -f Dockerfile

  # Validate JavaScript files
  - jsonlint server.js
  
  # Validate CoffeeScript files
  - coffeelint server.coffee
